FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG VISION_MODEL="gemma-4-31b-it"
ARG VISION_PROXY_URL="https://caption-proxy.hackathon-caption-pipe.workers.dev/vision"
ARG VISION_PROXY_TOKEN="1f633ad1c7aabec805dd3cec23486fa0f809e8d7b51aaf1347408d6c784c216f"
ARG OPENAI_PROXY_URL="https://caption-proxy.hackathon-caption-pipe.workers.dev/openai/responses"
ARG OPENAI_PROXY_TOKEN="1f633ad1c7aabec805dd3cec23486fa0f809e8d7b51aaf1347408d6c784c216f"
ARG OPENAI_CAPTION_MODEL="gpt-5.5"
ARG OPENAI_JUDGE_MODEL="gpt-5.5"
ARG CAPTION_PIPELINE_MODE="verified_scene"
ARG OBSERVATION_CAPTION_MODE="combined"
ARG ENABLE_VIDEO_NORMALIZATION="true"
ARG MAX_FRAMES_PER_VIDEO="12"
ARG MAX_CONCURRENT_JOBS="3"
ARG RUN_JUDGE_CHECKS="true"
ARG LOG_MODEL_IO="false"

ENV VISION_MODEL=${VISION_MODEL}
ENV VISION_PROXY_URL=${VISION_PROXY_URL}
ENV VISION_PROXY_TOKEN=${VISION_PROXY_TOKEN}
ENV OPENAI_PROXY_URL=${OPENAI_PROXY_URL}
ENV OPENAI_PROXY_TOKEN=${OPENAI_PROXY_TOKEN}
ENV OPENAI_CAPTION_MODEL=${OPENAI_CAPTION_MODEL}
ENV OPENAI_JUDGE_MODEL=${OPENAI_JUDGE_MODEL}
ENV CAPTION_PIPELINE_MODE=${CAPTION_PIPELINE_MODE}
ENV OBSERVATION_CAPTION_MODE=${OBSERVATION_CAPTION_MODE}
ENV ENABLE_VIDEO_NORMALIZATION=${ENABLE_VIDEO_NORMALIZATION}
ENV MAX_FRAMES_PER_VIDEO=${MAX_FRAMES_PER_VIDEO}
ENV MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS}
ENV RUN_JUDGE_CHECKS=${RUN_JUDGE_CHECKS}
ENV LOG_MODEL_IO=${LOG_MODEL_IO}

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /input /output

ENTRYPOINT ["python", "main.py"]
