FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV APP_NAME="GemmaCaption-Pipe"

ARG LLM_PROVIDER="openrouter"
ARG FIREWORKS_MODEL="accounts/fireworks/models/kimi-k2p6"
ARG OPENROUTER_MODEL="google/gemma-4-31b-it"
ARG JUDGE_LLM_PROVIDER="fireworks"
ARG JUDGE_MODEL="accounts/fireworks/models/kimi-k2p6"
ARG FIREWORKS_REASONING_EFFORT="none"
ARG FIREWORKS_TEMPERATURE="0.2"
ARG FIREWORKS_CREATIVE_TEMPERATURE="0.4"
ARG FIREWORKS_VISION_MAX_TOKENS="20000"
ARG FIREWORKS_CAPTION_MAX_TOKENS="20000"
ARG FIREWORKS_JUDGE_MAX_TOKENS="20000"
ARG CAPTION_ACCEPTANCE_THRESHOLD="0.94"
ARG ENABLE_VIDEO_NORMALIZATION="false"
ARG MAX_FRAMES_PER_VIDEO="12"
ARG MAX_CONCURRENT_JOBS="3"
ARG FIREWORKS_TIMEOUT_SECONDS="120"
ARG FIREWORKS_QUEUE_TIMEOUT_SECONDS="60"
ARG FIREWORKS_MAX_RETRIES="2"
ARG LOG_MODEL_IO="false"

ENV LLM_PROVIDER=${LLM_PROVIDER}
ENV FIREWORKS_MODEL=${FIREWORKS_MODEL}
ENV OPENROUTER_MODEL=${OPENROUTER_MODEL}
ENV JUDGE_LLM_PROVIDER=${JUDGE_LLM_PROVIDER}
ENV JUDGE_MODEL=${JUDGE_MODEL}
ENV FIREWORKS_REASONING_EFFORT=${FIREWORKS_REASONING_EFFORT}
ENV FIREWORKS_TEMPERATURE=${FIREWORKS_TEMPERATURE}
ENV FIREWORKS_CREATIVE_TEMPERATURE=${FIREWORKS_CREATIVE_TEMPERATURE}
ENV FIREWORKS_VISION_MAX_TOKENS=${FIREWORKS_VISION_MAX_TOKENS}
ENV FIREWORKS_CAPTION_MAX_TOKENS=${FIREWORKS_CAPTION_MAX_TOKENS}
ENV FIREWORKS_JUDGE_MAX_TOKENS=${FIREWORKS_JUDGE_MAX_TOKENS}
ENV CAPTION_ACCEPTANCE_THRESHOLD=${CAPTION_ACCEPTANCE_THRESHOLD}
ENV ENABLE_VIDEO_NORMALIZATION=${ENABLE_VIDEO_NORMALIZATION}
ENV MAX_FRAMES_PER_VIDEO=${MAX_FRAMES_PER_VIDEO}
ENV MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS}
ENV FIREWORKS_TIMEOUT_SECONDS=${FIREWORKS_TIMEOUT_SECONDS}
ENV FIREWORKS_QUEUE_TIMEOUT_SECONDS=${FIREWORKS_QUEUE_TIMEOUT_SECONDS}
ENV FIREWORKS_MAX_RETRIES=${FIREWORKS_MAX_RETRIES}
ENV LOG_MODEL_IO=${LOG_MODEL_IO}

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /input /output

ENTRYPOINT ["python", "main.py"]
