FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG GOOGLE_GEMINI_VISION_MODEL="gemma-4-31b-it"
ARG GOOGLE_GEMINI_PROXY_URL="https://caption-proxy.hackathon-caption-pipe.workers.dev/google/v1beta/interactions"
ARG GOOGLE_GEMINI_PROXY_TOKEN="1f633ad1c7aabec805dd3cec23486fa0f809e8d7b51aaf1347408d6c784c216f"
ARG OPENAI_PROXY_URL="https://caption-proxy.hackathon-caption-pipe.workers.dev/openai/responses"
ARG OPENAI_FINAL_CAPTION_MODEL="gpt-5.4-mini-2026-03-17"
ARG OPENAI_PROXY_TOKEN="1f633ad1c7aabec805dd3cec23486fa0f809e8d7b51aaf1347408d6c784c216f"
ARG OPENAI_TIMEOUT_SECONDS="45"
ARG OPENAI_MAX_RETRIES="1"
ARG OPENAI_TEMPERATURE="0.2"
ARG SIMPLIFIED_PIPELINE_ENABLED="false"
ARG ENABLE_VIDEO_NORMALIZATION="false"
ARG MAX_FRAMES_PER_VIDEO="12"
ARG MIN_FRAMES_PER_VIDEO="6"
ARG MAX_CONCURRENT_JOBS="3"
ARG PIPELINE_SEGMENT_COUNT="3"
ARG LOG_MODEL_IO="true"

ENV GOOGLE_GEMINI_VISION_MODEL=${GOOGLE_GEMINI_VISION_MODEL}
ENV GOOGLE_GEMINI_PROXY_URL=${GOOGLE_GEMINI_PROXY_URL}
ENV GOOGLE_GEMINI_PROXY_TOKEN=${GOOGLE_GEMINI_PROXY_TOKEN}
ENV OPENAI_PROXY_URL=${OPENAI_PROXY_URL}
ENV OPENAI_FINAL_CAPTION_MODEL=${OPENAI_FINAL_CAPTION_MODEL}
ENV OPENAI_PROXY_TOKEN=${OPENAI_PROXY_TOKEN}
ENV OPENAI_TIMEOUT_SECONDS=${OPENAI_TIMEOUT_SECONDS}
ENV OPENAI_MAX_RETRIES=${OPENAI_MAX_RETRIES}
ENV OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
ENV SIMPLIFIED_PIPELINE_ENABLED=${SIMPLIFIED_PIPELINE_ENABLED}
ENV ENABLE_VIDEO_NORMALIZATION=${ENABLE_VIDEO_NORMALIZATION}
ENV MAX_FRAMES_PER_VIDEO=${MAX_FRAMES_PER_VIDEO}
ENV MIN_FRAMES_PER_VIDEO=${MIN_FRAMES_PER_VIDEO}
ENV MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS}
ENV PIPELINE_SEGMENT_COUNT=${PIPELINE_SEGMENT_COUNT}
ENV LOG_MODEL_IO=${LOG_MODEL_IO}

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Pre-create standard mount points used by the batch harness.
RUN mkdir -p /input /output

ENTRYPOINT ["python", "main.py"]
